# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e6ca2b7c494e2d04fc058dc544604c3dd1c332d353331304a42ef75fe33a1e1b471b48f713d3983fa6a0a98a8fba24660b0f03c9577ec2cc3ed3b88c95a488d

test:
  secret_key_base: 244f0141d719d894cd2ab72429e5024601b34bed986abeef6d92e883e67fca001ada243a0b74e9a18a028f4bb7b847b1f6d26c2020569b4e08e220d2cc63ec4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
